# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8e09caf2fee0a5de2a03d1d1cd9339a6608b24a7f46dc56df5575a3a5c16c6d124746b001cf7fc69fed353f50fc454eca8b385edf41693e7ab6abcd15b73f87

test:
  secret_key_base: 22e38cba76f89f579e8713b754e76e4df19d523804dd18c7f173fc9b43f03ad6e5a25d0ac5f49b4749c59cfa366ad5704e6165d5cc42f12b2e908d3446e52ff3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
